### ISSUE TITLE
Does now allow for ordering Ginger Naan

### ISSUE THREAD

**Issue by KyleBrandon** [jonmbake/express-survey#4]
When submitting my order for the latest lunch and learn I found, to my utter dismay, that I was not able to select my favorite Ginger Naan.

I would request that this feature be added back into the product for the next release as my lunch workflow is utterly dependent on my Ginger Naan.

Thank you,
Kyle

**Comment by jonmbake** [comment]
Ha!  This is awesome!

Defining options of a field is not part of the framework;  it is the user of the framework's responsibility to define the correct field options (in `json/field_sets`).  I would talk to the guy using the framework for lunch orders and make sure he knows how it works.

**Comment by jthughey** [comment]
@KyleBrandon I think a reasonable work around is to select "Garlic Naan".  That's what I've been doing to mitigate this issue and it's been extremely successful.
